table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	measure 'Sales Amount' = SUM(Sales[SalesAmount])
		formatString: $#,##0
		lineageTag: e2f6dffc-81fd-4c89-a841-14b136e7a8f0

	measure 'Sales Amount PY' = CALCULATE([Sales Amount], SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: $#,##0
		lineageTag: 9ff3016c-ca80-4924-91df-613d9347bdbd

	measure 'Sales YoY Growth %' =
		VAR CurrentYearSales = [Sales Amount]
		VAR PriorYearSales = [Sales Amount PY]
		RETURN
		IF(
		    ISBLANK(PriorYearSales) || PriorYearSales = 0,
		    BLANK(),
		    DIVIDE(CurrentYearSales - PriorYearSales, PriorYearSales)
		)
		formatString: 0.0%
		lineageTag: cb5528df-6971-4f67-9601-1ac51e87283d

	measure 'Total Order Quantity' = SUM(Sales[OrderQty])
		formatString: #,##0
		lineageTag: 1ec4f928-0317-450a-b6f9-5a070d451850

	measure 'Total Revenue' = SUM(Sales[SalesAmount])
		formatString: $#,##0
		lineageTag: 1013eba5-9ca2-4a1c-b403-38043fd73944

	measure 'Average Order Value' = DIVIDE([Sales Amount], DISTINCTCOUNT(Sales[SalesOrderNumber]))
		formatString: $#,##0.00
		lineageTag: 9771c714-3049-4147-8f2f-84499286e2a6

	measure 'Total Product Cost' = SUM(Sales[TotalProductCost])
		formatString: $#,##0.00
		lineageTag: 44385068-c667-4a4c-afc9-e60debdede81

	measure 'Profit Margin %' =
		VAR Revenue = [Sales Amount]
		VAR Cost = [Total Product Cost]
		RETURN
		IF(
		    ISBLANK(Revenue) || Revenue = 0,
		    BLANK(),
		    DIVIDE(Revenue - Cost, Revenue)
		)
		formatString: 0.00%
		lineageTag: 69b910a8-49f6-46e5-bd48-ce9713c87f21

	measure 'Total Customers' = DISTINCTCOUNT(Sales[CustomerKey])
		formatString: #,##0
		lineageTag: 421a403d-86fc-46e2-b9e8-c5a79a863d9a

	/// Calculates the average sales amount per transaction by dividing total sales amount by number of transactions
	measure 'Average Sale Amount' = DIVIDE([Sales Amount], COUNTROWS(Sales))
		formatString: $#,##0.00
		lineageTag: 3fe685df-9c9c-4e2f-9b24-36e1486fd590

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

