table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	/// Simple test measure to validate Azure Analysis Services integration with GitHub Actions
	measure 'Test AAS Integration' = SUM(Sales[SalesAmount])
		formatString: $#,##0.00
		lineageTag: bc8e2501-8412-4470-b824-054914fb46de

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

