table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	/// Total sales amount - base measure for time intelligence calculations
	measure 'Sales Amount' = SUM(Sales[SalesAmount])
		formatString: $#,##0
		lineageTag: aac5fd2c-f734-47db-a1d5-0e3a9b528c61

	/// Sales amount for the same period last year
	measure 'Sales Amount LY' = CALCULATE([Sales Amount], SAMEPERIODLASTYEAR('Date'[DateKey]))
		formatString: $#,##0
		lineageTag: 7a442c9f-6bbe-427f-b1d4-f58c5eaed6b1

	/// Year-over-year sales growth percentage compared to same period last year
	measure 'Sales YoY Growth %' =
		VAR CurrentYear = [Sales Amount]
		VAR LastYear = [Sales Amount LY]
		RETURN
		IF(
		    ISBLANK(LastYear) || LastYear = 0,
		    BLANK(),
		    DIVIDE(CurrentYear - LastYear, LastYear)
		)
		formatString: 0.0%
		lineageTag: 2a65009c-979e-4964-ae94-7055fe2fed39

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

