table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	/// Total quantity of products sold
	measure 'Sales Volume' = SUM(Sales[OrderQuantity])
		formatString: #,##0
		lineageTag: b83775ba-2b80-484a-a7ef-9cda0afa0c2b

	/// Gross profit margin percentage
	measure 'Profit Margin %' =
		DIVIDE(
		    SUM(Sales[SalesAmount]) - SUM(Sales[TotalProductCost]),
		    SUM(Sales[SalesAmount])
		)
		formatString: 0.0%
		lineageTag: abee26c9-d5c0-48a8-9503-76952a018a21

	/// Normalized sales volume score (0-100 scale)
	measure 'Sales Volume Score' =
		VAR CurrentVolume = [Sales Volume]
		VAR MaxVolume = 
		    CALCULATE(
		        MAX([Sales Volume]),
		        REMOVEFILTERS(Product)
		    )
		RETURN
		    IF(
		        ISBLANK(CurrentVolume) || MaxVolume = 0,
		        BLANK(),
		        DIVIDE(CurrentVolume, MaxVolume) * 100
		    )
		formatString: 0.0
		lineageTag: be117cbb-56cf-4648-a304-068ae0b2ff78

	/// Normalized profit margin score (0-100 scale)
	measure 'Profit Margin Score' =
		VAR CurrentMargin = [Profit Margin %]
		VAR MaxMargin = 
		    CALCULATE(
		        MAX([Profit Margin %]),
		        REMOVEFILTERS(Product)
		    )
		RETURN
		    IF(
		        ISBLANK(CurrentMargin) || MaxMargin = 0,
		        BLANK(),
		        DIVIDE(CurrentMargin, MaxMargin) * 100
		    )
		formatString: 0.0
		lineageTag: 5a3edaf7-0045-4aee-a7cd-d4935be06793

	/// Customer satisfaction proxy based on return rate (0-100 scale)
	measure 'Customer Satisfaction Score' =
		VAR TotalProducts = DISTINCTCOUNT(Sales[ProductKey])
		VAR ProductsWithReturns = 
		    CALCULATE(
		        DISTINCTCOUNT(Sales[ProductKey]),
		        Sales[OrderQuantity] < 0
		    )
		VAR ReturnRate = DIVIDE(ProductsWithReturns, TotalProducts)
		RETURN
		    IF(
		        ISBLANK(TotalProducts) || TotalProducts = 0,
		        BLANK(),
		        (1 - COALESCE(ReturnRate, 0)) * 100
		    )
		formatString: 0.0
		lineageTag: dfcb8582-59e8-42ed-950f-a975a09ac020

	/// Composite performance score weighted across sales volume (40%), profit margin (35%), and customer satisfaction (25%)
	measure 'Product Performance Score' =
		VAR VolumeScore = [Sales Volume Score]
		VAR MarginScore = [Profit Margin Score]
		VAR SatisfactionScore = [Customer Satisfaction Score]
		VAR ValidScores = 
		    (IF(NOT ISBLANK(VolumeScore), 1, 0)) +
		    (IF(NOT ISBLANK(MarginScore), 1, 0)) +
		    (IF(NOT ISBLANK(SatisfactionScore), 1, 0))
		RETURN
		    IF(
		        ValidScores = 0,
		        BLANK(),
		        (
		            COALESCE(VolumeScore, 0) * 0.4 +
		            COALESCE(MarginScore, 0) * 0.35 +
		            COALESCE(SatisfactionScore, 0) * 0.25
		        ) * (3 / ValidScores)
		    )
		formatString: 0.0
		lineageTag: 09920dac-cf27-49bb-a723-e7378f5eb14d

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

