table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	/// Count of unique customers who made purchases in the current month
	measure 'Unique Customers Current Month' =
		CALCULATE(
		    DISTINCTCOUNT(Sales[CustomerKey]),
		    DATESMTD('Date'[Date])
		)
		formatString: #,##0
		lineageTag: 0562d5d4-c60c-4632-9b4e-d65a2f595931

	/// Count of unique customers who made purchases in the previous month
	measure 'Unique Customers Previous Month' =
		CALCULATE(
		    DISTINCTCOUNT(Sales[CustomerKey]),
		    DATEADD(
		        DATESMTD('Date'[Date]),
		        -1,
		        MONTH
		    )
		)
		formatString: #,##0
		lineageTag: 928d4168-9a65-49d1-841a-403ac1f4ab97

	/// Count of customers who made purchases in both current and previous month
	measure 'Retained Customers' =
		VAR CustomersCurrentMonth = 
		    CALCULATETABLE(
		        VALUES(Sales[CustomerKey]),
		        DATESMTD('Date'[Date])
		    )
		VAR CustomersPreviousMonth = 
		    CALCULATETABLE(
		        VALUES(Sales[CustomerKey]),
		        DATEADD(
		            DATESMTD('Date'[Date]),
		            -1,
		            MONTH
		        )
		    )
		RETURN
		    COUNTROWS(
		        INTERSECT(
		            CustomersCurrentMonth,
		            CustomersPreviousMonth
		        )
		    )
		formatString: #,##0
		lineageTag: 73de483e-0153-4355-90db-e316ab0ec28e

	/// Percentage of customers from previous month who made purchases in current month
	measure 'Customer Retention Rate' =
		DIVIDE(
		    [Retained Customers],
		    [Unique Customers Previous Month],
		    BLANK()
		)
		formatString: 0.0%
		lineageTag: 70f1c3a8-e15d-4bfb-85dd-4b2f3fade592

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

