table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	/// Total sales revenue amount
	measure 'Sales Amount' = SUM(Sales[SalesAmount])
		formatString: $#,##0.00
		lineageTag: ebbf8fa4-b5d7-4170-b15e-bdf5a1a5ab12

	/// Total cost of products sold
	measure 'Total Product Cost' = SUM(Sales[TotalProductCost])
		formatString: $#,##0.00
		lineageTag: beae09b4-bf16-44f8-b56f-6f75e180ec2d

	/// Gross profit calculated as sales amount minus total product cost
	measure 'Gross Profit' = [Sales Amount] - [Total Product Cost]
		formatString: $#,##0.00
		lineageTag: 7d68a05a-73e5-40cc-88a1-26377bfc99c4

	/// Profit margin percentage calculated as gross profit divided by sales amount
	measure 'Profit Margin %' = DIVIDE([Gross Profit], [Sales Amount])
		formatString: 0.00%
		lineageTag: 057473cd-f619-473e-a493-cb4fefc25c62

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

