table 'Sales'
	lineageTag: de9763d5-b29f-4743-8ed4-7fcfe6768abd

	measure 'Sales Amount by Due Date' = ```
		lineageTag: c2fe3283-9d89-4bee-b219-09de50cc38c5

	/// Total sales revenue - base measure for velocity calculations
	measure 'Sales Amount' = SUM(Sales[SalesAmount])
		formatString: $#,##0
		lineageTag: 31e8889f-58c3-41d3-9e90-d15fd601e87c

	/// Sales amount from 30 days prior, used for velocity calculation
	measure 'Sales Amount 30 Days Ago' =
		CALCULATE(
		    [Sales Amount],
		    DATEADD('Date'[Date], -30, DAY)
		)
		formatString: $#,##0
		lineageTag: 4a98a7b5-b873-4ccd-a94f-f0e5975ecf92

	/// Rate of sales growth over a rolling 30-day period, expressed as percentage change
	measure 'Sales Velocity 30 Day' =
		VAR CurrentSales = [Sales Amount]
		VAR PriorSales = [Sales Amount 30 Days Ago]
		VAR VelocityRate = 
		    IF(
		        AND(NOT(ISBLANK(CurrentSales)), NOT(ISBLANK(PriorSales))),
		        DIVIDE(CurrentSales - PriorSales, PriorSales),
		        BLANK()
		    )
		RETURN VelocityRate
		formatString: 0.00%
		lineageTag: d4f9525c-b56e-45c1-98b7-dab4d3292b22

	partition Sales-12135db7-a44d-4ce1-8b1f-bf4fa607dc66 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jterh\OneDrive - Microsoft\_Corp Era\Power BI\AW2020 Sample\Sales\AdventureWorks Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

